name: Deploy to GitHub Pages

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag
        id: vars
        run: echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Copy files to version directory
        run: |
          mkdir -p ${{ env.RELEASE_TAG }}
          cp -r * ${{ env.RELEASE_TAG }}/ || true  # Копируем все файлы в папку v{tag}

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .

